apiVersion: v1
kind: Pod
metadata:
  name: onfailure-pod
spec:
  containers:
    - name: failing-container
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep 10; exit 1"] # 0이 아니고 1이라 비정상 종료
  restartPolicy: Never
