apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddoddo-chart.fullname" . }}-backend-secret
  labels:
    {{- include "ddoddo-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.backend.secret.DB_PASSWORD | quote }}
  JWT_SECRET_KEY: {{ .Values.backend.secret.JWT_SECRET_KEY | quote }}
  CLOUDFLARE_ACCESS_KEY_ID: {{ .Values.backend.secret.CLOUDFLARE_ACCESS_KEY_ID | quote }}
  CLOUDFLARE_SECRET_ACCESS_KEY: {{ .Values.backend.secret.CLOUDFLARE_SECRET_ACCESS_KEY | quote }}
