apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ddoddo-chart.fullname" . }}-db-config
  labels:
    {{- include "ddoddo-chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.db.config.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.db.config.POSTGRES_USER | quote }}
