apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddoddo-chart.fullname" . }}-db-secret
  labels:
    {{- include "ddoddo-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.db.secret.POSTGRES_PASSWORD | quote }}
