apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ddoddo-chart.fullname" . }}-backend
  labels:
    app: {{ include "ddoddo-chart.name" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ddoddo-chart.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "ddoddo-chart.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "ddoddo-chart.fullname" . }}-backend-config
            - secretRef:
                name: {{ include "ddoddo-chart.fullname" . }}-backend-secret
