apiVersion: v1
kind: Secret
metadata:
  name: ddoddo-backend-secret
type: Opaque
data:
  DB_PASSWORD: cGFzczEyMzQ=
  JWT_SECRET_KEY: YVNzVkV3QUxFNlBma2xaZnZ1MTY2UXNyRmhBRkVPWjd2dmdURlpMNWkvZmpoV1RYZnloLzMwK245alNuQVJZalR3OHdnU1pLdWg3RzZsZzVRemU5SlE9PQ==
  CLOUDFLARE_ACCESS_KEY_ID: YWIzN2NjMGRiYTc2ODIwMDE1NjMwY2M1NjM0ZTIwYzU=
  CLOUDFLARE_SECRET_ACCESS_KEY: ZWMzMTgxNWFjZjkyNGU3NDM3YmEwYzgzMDczMzkzMTcyNzI2Mjc4NWMzNjhlNzkyYmY0NDU5OGQyNzA3ODkyYg==
