# Step 1: Build jar file
FROM gradle:8.3-jdk17 AS builder

WORKDIR /app

COPY build.gradle settings.gradle /app/
RUN gradle build --no-daemon || true

COPY . /app
RUN gradle clean bootJar --no-daemon

# Step 2: 실행용 이미지
FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
