apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-db # StatefulSet 이름
spec:
  serviceName: "todo-db-svc" # 반드시 Headless Service 이름과 일치해야 함
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: todo-list-config
            - secretRef:
                name: todo-list-secret
          volumeMounts:
            - name: todo-db-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: todo-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard" # Minikube 또는 클러스터에 맞는 StorageClass
        resources:
          requests:
            storage: 1Gi
